name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type Check & Build
        run: npm run build --if-present

      - name: Unit & Component Tests
        run: npm test -- --coverage

      - name: Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 120
          browser: chrome
          record: false
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      - name: Upload Coverage to Codecov (optional)
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,component
          fail_ci_if_error: false 